export const BOOKS_ADD_ITEMS_TO_COLLECTION = 'BOOKS_ADD_ITEMS_TO_COLLECTION';
export const BOOKS_SET_COLLECTION = 'BOOKS_SET_COLLECTION';
export const BOOKS_FILTER_COLLECTION = 'BOOKS_FILTER_COLLECTION';