export const FILTERS_ADD_SELECTED = 'FILTERS_ADD_SELECTED';
export const FILTERS_REMOVE_SELECTED = 'FILTERS_REMOVE_SELECTED';
export const FILTERS_SET_SELECTED_FROM_REQUEST = 'FILTERS_SET_SELECTED_FROM_REQUEST';