export const FILTERS_SET_COLLECTION = 'FILTERS_SET_COLLECTION';
export const FILTERS_ADD_SELECTED = 'FILTERS_ADD_SELECTED';
export const FILTERS_REMOVE_SELECTED = 'FILTERS_REMOVE_SELECTED';
export const FILTERS_SET_FROM_INCLUDES = 'FILTERS_SET_FROM_INCLUDES';