export const FILTERS_SET_COLLECTION = 'FILTERS_SET_COLLECTION';
export const FILTERS_ADD_SELECTED = 'FILTERS_ADD_SELECTED';
export const FILTERS_REMOVE_SELECTED = 'FILTERS_REMOVE_SELECTED';
export const FILTERS_SET_FROM_BOOK_INCLUDES = 'FILTERS_SET_FROM_BOOK_INCLUDES';
export const FILTERS_SET_FROM_AUTHOR_INCLUDES = 'FILTERS_SET_FROM_AUTHOR_INCLUDES';