export const AUTHORS_ADD_ITEMS_TO_COLLECTION = 'AUTHORS_ADD_ITEMS_TO_COLLECTION';
export const AUTHORS_SET_COLLECTION = 'AUTHORS_SET_COLLECTION';
export const AUTHORS_FILTER_COLLECTION = 'AUTHORS_FILTER_COLLECTION';